name: ff-spawn
version: '1.0.0'
main: com.haksndot.ffspawn.FFSpawn
api-version: '1.21'
authors: [Haksndot]
description: Flexible Foundation Spawn - random spawn zones with GriefPrevention awareness

softdepend:
  - GriefPrevention

commands:
  ffspawn:
    description: Manage FFSpawn settings
    usage: /<command> <reload|addzone|removezone|list|test>
    permission: ffspawn.admin
    aliases: [ffs, spawn]

permissions:
  ffspawn.admin:
    description: Allows access to FFSpawn admin commands
    default: op
  ffspawn.bypass:
    description: Bypass random spawn (use normal respawn behavior)
    default: false
  ffspawn.place:
    description: Allows placing spawn blocks
    default: true
